name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"

    - shell: bash
      run: pnpm add -g turbo bun@1.1.26

    - shell: bash
      run: pnpm install --frozen-lockfile

    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        flavor: release
        # flutter-version-file: packages/dart/pubspec.yaml
