services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    environment:
      # POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      # POSTGRES_DB: socketless
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    # network_mode: "host"
    volumes:
      - dragonfly-data:/data
volumes:
  dragonfly-data:
  postgres-data:
