services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    restart: always
    environment:
      # POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      # POSTGRES_DB: socketless
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
