name: socketless_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/wosherco/socketless

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  web_socket_channel: ^3.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
