import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "category",
      label: "Introduction",
      link: { type: "doc", id: "introduction" },
      items: ["concepts", "use-case", "open-source", "self-hosting"],
    },
    {
      type: "category",
      label: "Getting Started",
      items: [{ type: "autogenerated", dirName: "getting-started" }],
    },
    {
      type: "category",
      label: "Guides",
      link: { type: "doc", id: "guides" },
      items: [{ type: "autogenerated", dirName: "guides" }],
    },
    {
      type: "category",
      label: "Libraries",
      // link: { type: "doc", id: "libraries" },
      items: [{ type: "autogenerated", dirName: "libraries" }],
    },
    {
      type: "category",
      label: "Integrations",
      // link: { type: "doc", id: "libraries" },
      items: [{ type: "autogenerated", dirName: "integrations" }],
    },
    {
      type: "category",
      label: "Infrastructure",
      link: { type: "doc", id: "infrastructure" },
      items: ["locations"],
    },
  ],
};

export default sidebars;
