contact_links:
  - name: Feature request
    url: https://insigh.to/b/socketless
    about: Simple feature requests go on insigh.to.
  - name: Ask a question
    url: https://github.com/wosherco/socketless/discussions
    about: Ask questions and discuss with other community members
