name: Release - Canary

on:
  pull_request:
    types: [labeled]
    branches:
      - main

jobs:
  release:
    if: contains(github.event.pull_request.labels.*.name, 'release canary')
    timeout-minutes: 10
    name: Build & Publish a canary release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Check packages for common errors
        run: pnpm turbo --filter "./packages/*" build

      - name: Authenticate to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Publish canary releases
        run: node .github/release-canary.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
